"""Initial Migration

Revision ID: 0128704c894b
Revises: 
Create Date: 2026-07-07 01:16:15.258105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0128704c894b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_ibge', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pais_codigo_ibge'), 'pais', ['codigo_ibge'], unique=True)
    op.create_index(op.f('ix_pais_id'), 'pais', ['id'], unique=False)
    op.create_table('regiao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_ibge', sa.Integer(), nullable=True),
    sa.Column('sigla', sa.String(length=5), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regiao_codigo_ibge'), 'regiao', ['codigo_ibge'], unique=True)
    op.create_index(op.f('ix_regiao_id'), 'regiao', ['id'], unique=False)
    op.create_table('tb_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sistema_usuario', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=250), nullable=False),
    sa.Column('metodo', sa.String(length=10), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_auditoria_id'), 'tb_auditoria', ['id'], unique=False)
    op.create_table('tipo_logradouro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=True),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_logradouro_id'), 'tipo_logradouro', ['id'], unique=False)
    op.create_table('uf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_ibge', sa.Integer(), nullable=True),
    sa.Column('sigla', sa.String(length=2), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('regiao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regiao_id'], ['regiao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_index(op.f('ix_uf_codigo_ibge'), 'uf', ['codigo_ibge'], unique=True)
    op.create_index(op.f('ix_uf_id'), 'uf', ['id'], unique=False)
    op.create_table('mesorregiao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_ibge', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('uf_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uf_id'], ['uf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesorregiao_codigo_ibge'), 'mesorregiao', ['codigo_ibge'], unique=True)
    op.create_index(op.f('ix_mesorregiao_id'), 'mesorregiao', ['id'], unique=False)
    op.create_table('regiao_intermediaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_ibge', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('uf_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uf_id'], ['uf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regiao_intermediaria_codigo_ibge'), 'regiao_intermediaria', ['codigo_ibge'], unique=True)
    op.create_index(op.f('ix_regiao_intermediaria_id'), 'regiao_intermediaria', ['id'], unique=False)
    op.create_table('microrregiao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_ibge', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('mesorregiao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mesorregiao_id'], ['mesorregiao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microrregiao_codigo_ibge'), 'microrregiao', ['codigo_ibge'], unique=True)
    op.create_index(op.f('ix_microrregiao_id'), 'microrregiao', ['id'], unique=False)
    op.create_table('regiao_imediata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_ibge', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('regiao_intermediaria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regiao_intermediaria_id'], ['regiao_intermediaria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regiao_imediata_codigo_ibge'), 'regiao_imediata', ['codigo_ibge'], unique=True)
    op.create_index(op.f('ix_regiao_imediata_id'), 'regiao_imediata', ['id'], unique=False)
    op.create_table('municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_ibge', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('microrregiao_id', sa.Integer(), nullable=True),
    sa.Column('regiao_imediata_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['microrregiao_id'], ['microrregiao.id'], ),
    sa.ForeignKeyConstraint(['regiao_imediata_id'], ['regiao_imediata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipio_codigo_ibge'), 'municipio', ['codigo_ibge'], unique=True)
    op.create_index(op.f('ix_municipio_id'), 'municipio', ['id'], unique=False)
    op.create_table('tb_cep',
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('logradouro', sa.String(length=250), nullable=True),
    sa.Column('bairro', sa.String(length=150), nullable=True),
    sa.Column('localidade', sa.String(length=150), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('uf_codigo', sa.Integer(), nullable=True),
    sa.Column('municipio_codigo', sa.Integer(), nullable=True),
    sa.Column('tipo_logradouro_codigo', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_codigo'], ['municipio.id'], ),
    sa.ForeignKeyConstraint(['tipo_logradouro_codigo'], ['tipo_logradouro.id'], ),
    sa.ForeignKeyConstraint(['uf_codigo'], ['uf.id'], ),
    sa.PrimaryKeyConstraint('cep')
    )
    op.create_index(op.f('ix_tb_cep_cep'), 'tb_cep', ['cep'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_cep_cep'), table_name='tb_cep')
    op.drop_table('tb_cep')
    op.drop_index(op.f('ix_municipio_id'), table_name='municipio')
    op.drop_index(op.f('ix_municipio_codigo_ibge'), table_name='municipio')
    op.drop_table('municipio')
    op.drop_index(op.f('ix_regiao_imediata_id'), table_name='regiao_imediata')
    op.drop_index(op.f('ix_regiao_imediata_codigo_ibge'), table_name='regiao_imediata')
    op.drop_table('regiao_imediata')
    op.drop_index(op.f('ix_microrregiao_id'), table_name='microrregiao')
    op.drop_index(op.f('ix_microrregiao_codigo_ibge'), table_name='microrregiao')
    op.drop_table('microrregiao')
    op.drop_index(op.f('ix_regiao_intermediaria_id'), table_name='regiao_intermediaria')
    op.drop_index(op.f('ix_regiao_intermediaria_codigo_ibge'), table_name='regiao_intermediaria')
    op.drop_table('regiao_intermediaria')
    op.drop_index(op.f('ix_mesorregiao_id'), table_name='mesorregiao')
    op.drop_index(op.f('ix_mesorregiao_codigo_ibge'), table_name='mesorregiao')
    op.drop_table('mesorregiao')
    op.drop_index(op.f('ix_uf_id'), table_name='uf')
    op.drop_index(op.f('ix_uf_codigo_ibge'), table_name='uf')
    op.drop_table('uf')
    op.drop_index(op.f('ix_tipo_logradouro_id'), table_name='tipo_logradouro')
    op.drop_table('tipo_logradouro')
    op.drop_index(op.f('ix_tb_auditoria_id'), table_name='tb_auditoria')
    op.drop_table('tb_auditoria')
    op.drop_index(op.f('ix_regiao_id'), table_name='regiao')
    op.drop_index(op.f('ix_regiao_codigo_ibge'), table_name='regiao')
    op.drop_table('regiao')
    op.drop_index(op.f('ix_pais_id'), table_name='pais')
    op.drop_index(op.f('ix_pais_codigo_ibge'), table_name='pais')
    op.drop_table('pais')
    # ### end Alembic commands ###
