"""Add sistemas autorizados

Revision ID: f27cb25938e0
Revises: 0128704c894b
Create Date: 2026-07-08 16:25:20.003016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27cb25938e0'
down_revision: Union[str, Sequence[str], None] = '0128704c894b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sistemas_autorizados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_sistema', sa.String(length=100), nullable=False),
    sa.Column('chave_hash', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sistemas_autorizados_id'), 'sistemas_autorizados', ['id'], unique=False)
    op.create_index(op.f('ix_sistemas_autorizados_nome_sistema'), 'sistemas_autorizados', ['nome_sistema'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sistemas_autorizados_nome_sistema'), table_name='sistemas_autorizados')
    op.drop_index(op.f('ix_sistemas_autorizados_id'), table_name='sistemas_autorizados')
    op.drop_table('sistemas_autorizados')
    # ### end Alembic commands ###
